import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.css";
import { SelectedTimeProvider } from "./contexts/SelectedTime";

const rubik = Rubik({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${rubik.className} bg-neutral-verydarkblue grid h-full place-content-center min-h-dvh text-[18px] `}
      >
        <SelectedTimeProvider>{children}</SelectedTimeProvider>
      </body>
    </html>
  );
}
